const fs = require('fs');
const path = require('path');

const ROOT = process.cwd();
const JS_DIR = path.join(ROOT, 'js');
const CSS_DIR = path.join(ROOT, 'css');
const HTML_FILE = path.join(ROOT, 'index.html');
const EXCLUDE_FILE = 'stats-generated.js';
const EXCLUDE_DIRS = new Set(['lib', 'scratch']);
const OUT_FILE = path.join(JS_DIR, EXCLUDE_FILE);

function countLinesInDir(dir, ext) {
  let total = 0;
  let fileCount = 0;
  function walk(d) {
    let entries;
    try { entries = fs.readdirSync(d); } catch { return; }
    for (const entry of entries) {
      if (entry === EXCLUDE_FILE) continue;
      const fp = path.join(d, entry);
      const stat = fs.statSync(fp);
      if (stat.isDirectory()) {
        if (!EXCLUDE_DIRS.has(entry)) walk(fp);
      } else if (entry.endsWith(ext)) {
        fileCount++;
        total += fs.readFileSync(fp, 'utf8').split('\n').length;
      }
    }
  }
  walk(dir);
  return { total, fileCount };
}

const js = countLinesInDir(JS_DIR, '.js');
const css = countLinesInDir(CSS_DIR, '.css');

let htmlLines = 0;
try {
  htmlLines = fs.readFileSync(HTML_FILE, 'utf8').split('\n').length;
} catch {}

fs.writeFileSync(OUT_FILE,
  `// Auto-generated by count-lines.js — do not edit\n` +
  `TOTAL_JS_LINES = ${js.total};\n` +
  `TOTAL_CSS_LINES = ${css.total};\n` +
  `TOTAL_HTML_LINES = ${htmlLines};\n`);

console.log(
  `count-lines: JS ${js.total} lines (${js.fileCount} files), ` +
  `CSS ${css.total} lines (${css.fileCount} files), ` +
  `HTML ${htmlLines} lines → ${OUT_FILE}`);
