const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const ROOT = process.cwd();
const JS_DIR = path.join(ROOT, 'js');
const CSS_DIR = path.join(ROOT, 'css');
const HTML_FILE = path.join(ROOT, 'index.html');
const EXCLUDE_FILE = 'stats-generated.js';
const EXCLUDE_DIRS = new Set(['lib', 'scratch']);
const OUT_FILE = path.join(JS_DIR, EXCLUDE_FILE);

function countLinesInDir(dir, ext) {
  let total = 0;
  let fileCount = 0;
  function walk(d) {
    let entries;
    try { entries = fs.readdirSync(d); } catch { return; }
    for (const entry of entries) {
      if (entry === EXCLUDE_FILE) continue;
      if (path.basename(entry) !== entry) continue;
      const fp = path.join(d, path.basename(entry));
      const stat = fs.statSync(fp);
      if (stat.isDirectory()) {
        if (!EXCLUDE_DIRS.has(entry)) walk(fp);
      } else if (entry.endsWith(ext)) {
        fileCount++;
        total += fs.readFileSync(fp, 'utf8').split('\n').length;
      }
    }
  }
  walk(dir);
  return { total, fileCount };
}

function git(cmd) {
  try { return execFileSync('git', cmd.split(' '), { cwd: ROOT, encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'] }).trim(); }
  catch { return null; }
}

function countLinesFromPrevCommit(dirRel, ext) {
  const tree = git(`ls-tree -r --name-only HEAD~1 -- ${dirRel}`);
  if (!tree) return null;
  let total = 0;
  for (const file of tree.split('\n')) {
    if (!file.endsWith(ext)) continue;
    if (file.includes(EXCLUDE_FILE)) continue;
    const parts = file.split('/');
    if (parts.some(p => EXCLUDE_DIRS.has(p))) continue;
    const content = git(`show HEAD~1:${file}`);
    if (content !== null) total += content.split('\n').length;
  }
  return total;
}

const js = countLinesInDir(JS_DIR, '.js');
const css = countLinesInDir(CSS_DIR, '.css');

let htmlLines = 0;
try {
  htmlLines = fs.readFileSync(HTML_FILE, 'utf8').split('\n').length;
} catch {}

let jsDelta = 0, cssDelta = 0, htmlDelta = 0;
const prevJs = countLinesFromPrevCommit('js', '.js');
const prevCss = countLinesFromPrevCommit('css', '.css');
const prevHtml = git('show HEAD~1:index.html');
const prevHtmlLines = prevHtml !== null ? prevHtml.split('\n').length : null;

if (prevJs !== null) jsDelta = js.total - prevJs;
if (prevCss !== null) cssDelta = css.total - prevCss;
if (prevHtmlLines !== null) htmlDelta = htmlLines - prevHtmlLines;

function fmtDelta(n) {
  if (n === 0) return '';
  return n > 0 ? `+${n.toLocaleString()}` : n.toLocaleString();
}

fs.writeFileSync(OUT_FILE,
  `// Auto-generated by count-lines.js — do not edit\n` +
  `TOTAL_JS_LINES = ${js.total};\n` +
  `TOTAL_CSS_LINES = ${css.total};\n` +
  `TOTAL_HTML_LINES = ${htmlLines};\n` +
  `TOTAL_JS_LINES_DELTA = '${fmtDelta(jsDelta)}';\n` +
  `TOTAL_CSS_LINES_DELTA = '${fmtDelta(cssDelta)}';\n` +
  `TOTAL_HTML_LINES_DELTA = '${fmtDelta(htmlDelta)}';\n`);

console.log(
  `count-lines: JS ${js.total} (${fmtDelta(jsDelta)}) ${js.fileCount} files, ` +
  `CSS ${css.total} (${fmtDelta(cssDelta)}) ${css.fileCount} files, ` +
  `HTML ${htmlLines} (${fmtDelta(htmlDelta)}) → ${OUT_FILE}`);
